# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160824_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='website',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
