# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160828_2251'),
        ('api', '0004_auto_20160831_0217'),
    ]

    operations = [
    ]
