# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20160914_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='zip',
            new_name='zipcode',
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[(b'CG', b'Community Garden'), (b'FM', b"Farmer's Market"), (b'FB', b'Food Bank'), (b'GS', b'Grocery Store'), (b'SM', b'Super Market'), (b'CV', b'Convenience Store')], max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
