# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20160930_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(b'Mo', b'Monday'), (b'Tu', b'Tuesday'), (b'We', b'Wednesday'), (b'Th', b'Thursday'), (b'Fr', b'Friday'), (b'Sa', b'Saturday'), (b'Su', b'Sunday')], max_length=100)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
            ],
        ),
    ]
