# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-25 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170121_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
