# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-05 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170225_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address_2',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
