# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-05 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170405_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address_1',
            field=models.CharField(max_length=200),
        ),
    ]
