# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=80)),
                ('address_1', models.CharField(max_length=60)),
                ('address_2', models.CharField(blank=True, default='', max_length=40)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(blank=True, default='CA', max_length=2)),
                ('zip', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('category', models.CharField(choices=[('CG', 'Community Garden'), ('FM', "Farmer's Market"), ('FB', 'Food Bank'), ('GS', 'Grocery Store')], max_length=50)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
