# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160824_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address_1',
            field=models.CharField(default='111 Hollywood Dr', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='address_2',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('CG', 'Community Garden'), ('FM', "Farmer's Market"), ('FB', 'Food Bank'), ('GS', 'Grocery Store')], default='FB', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='Los Angeles', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=35.1111, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=181.1111, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(default='111-111-1111', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, default='CA', max_length=2),
        ),
        migrations.AddField(
            model_name='location',
            name='zip',
            field=models.CharField(default='90012', max_length=5),
            preserve_default=False,
        ),
    ]
