# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160824_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('CG', 'Community Garden'), ('FM', "Farmer's Market"), ('FB', 'Food Bank'), ('GS', 'Grocery Store'), ('CV', 'Convience Store')], max_length=50),
        ),
    ]
