# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160915_0412'),
        ('api', '0005_merge_20160919_2353'),
    ]

    operations = [
    ]
