# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20160922_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[(b'CG', b'Community Garden'), (b'FM', b"Farmer's Market"), (b'FB', b'Food Bank'), (b'GS', b'Grocery Store'), (b'SM', b'Super Market'), (b'OS', b'Other Stores')], max_length=50),
        ),
    ]
